services:
  database:
    container_name: "survey-dev"
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${SURVEY_API_DATABASE__USER}
      POSTGRES_PASSWORD: ${SURVEY_API_DATABASE__PASSWORD}
      POSTGRES_DB: ${SURVEY_API_DATABASE__DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: